name: '🚀 Apply Terraform'

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: >
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      env:
            TF_VAR_web_ui_repository_token: ${{ secrets.ACCESS_TOKEN }}
            TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
            TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
            TF_VAR_azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      env:
        TF_VAR_web_ui_repository_token: ${{ secrets.ACCESS_TOKEN }}
        TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      run: terraform plan -input=false -out=tfplan
      
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      env:
        TF_VAR_web_ui_repository_token: ${{ secrets.ACCESS_TOKEN }}
        TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      run: terraform apply -auto-approve -input=false
