name: '📦Requirements Terraform'

on:
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    env: 
      TF_VAR_web_ui_repository_token: ${{ secrets.ACCESS_TOKEN }}
      TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:

    - name: Set environment variables for Terraform
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4

    #- name: Azure login
    #  uses: azure/login@v2
    #  with:
    #    creds: >
    #        {
    #          "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
    #          "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
    #          "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
    #          "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
    #        }

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -input=false